version: "3.7"
services:

  kong:
    container_name: kong
    image: kong:3.1.0

    environment:
      - KONG_DATABASE=off
      - KONG_LOG_LEVEL=warn
      - KONG_NGINX_WORKER_PROCESSES=1
      - KONG_PLUGINS=bundled, shutdown-events
      - KONG_DECLARATIVE_CONFIG_STRING={"_format_version":"2.1"}
    volumes:
      - ./kong.yaml:/kong.yaml:rw
      - ./shutdown-events:/usr/local/share/lua/5.1/kong/plugins/shutdown-events

networks:
  default:
    name: kong
