name: CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Run tests
        run: |
          docker-compose up -d kong
          sleep 2
          docker-compose exec kong kong reload
          sleep 70
          docker-compose logs kong
          docker-compose down
